server:
  port: 58082
spring:
  application:
    name: wcdk-process
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:dm://localhost:25236/QXTD-PROCESS
    username: QXTD-PROCESS
    password: Qxtd@2026
    driver-class-name: dm.jdbc.driver.DmDriver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置多久进行一次空闲连接检测
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      # 配置连接在池中最大生存时间
      max-evictable-idle-time-millis: 900000
      # 配置连接有效性检测语句
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
        allow:
        url-pattern: /druid/*
      filter:
        stat:
          enabled: false
          # 慢 SQL 记录
          log-slow-sql: false
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: false

flowable:
  # 生产环境建议先由 DBA 初始化表结构，再改为 false
  database-schema-update: true
  async-executor-activate: false
  check-process-definitions: true
  process-definition-location-prefix: classpath*:/processes/
  process-definition-location-suffixes:
    - "**.bpmn20.xml"
  activity-font-name: 宋体
  label-font-name: 宋体
  annotation-font-name: 宋体

logging:
  level:
    org.flowable: debug
    org.flowable.common.engine.impl.db: debug
    org.flowable.common.engine.impl.persistence.entity: debug
    com.wcdk.proces: info

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wcdk:
  process:
    swagger:
      description: 流程引擎 服务接口文档
      title: 流程引擎接口文档
      version: 1.0
    strict-mode: true