CREATE TABLE WCDK_PROCESS_REQUEST (
    ID BIGINT NOT NULL,
    PROCESS_NO VARCHAR(64) NOT NULL,
    STARTER VARCHAR(64) NOT NULL,
    TASK_NAME VARCHAR(255) NOT NULL,
    BUSINESS_TITLE VARCHAR(1000) NOT NULL,
    FORM_DATA_JSON CLOB,
    STATUS VARCHAR(32) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64),
    CURRENT_TASK_ID VARCHAR(64),
    CURRENT_TASK_NAME VARCHAR(128),
    PROCESS_DEFINITION_KEY VARCHAR(128) NOT NULL,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_REQUEST PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_REQUEST IS '流程申请业务表';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_NO IS '流程申请编号';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.STARTER IS '流程发起人';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.TASK_NAME IS '任务名称';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.BUSINESS_TITLE IS '业务标题';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.FORM_DATA_JSON IS '动态表单数据JSON';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.STATUS IS '流程申请状态';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_INSTANCE_ID IS '流程实例ID';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CURRENT_TASK_ID IS '当前任务ID';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CURRENT_TASK_NAME IS '当前任务名称';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_DEFINITION_KEY IS '流程定义标识';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.UPDATE_TIME IS '更新时间';

CREATE UNIQUE INDEX UK_WCDK_PROCESS_REQUEST_NO ON WCDK_PROCESS_REQUEST(PROCESS_NO);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_PROC ON WCDK_PROCESS_REQUEST(PROCESS_INSTANCE_ID);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_DEF_KEY ON WCDK_PROCESS_REQUEST(PROCESS_DEFINITION_KEY);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_STATUS ON WCDK_PROCESS_REQUEST(STATUS);

CREATE TABLE WCDK_PROCESS_CLIENT (
    ID BIGINT NOT NULL,
    CLIENT_ID VARCHAR(64) NOT NULL,
    CLIENT_NAME VARCHAR(128) NOT NULL,
    CALLBACK_URL VARCHAR(500),
    AUTH_FLG CLOB,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_CLIENT PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_CLIENT IS '客户端回调绑定表';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CLIENT_ID IS '客户端标识';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CLIENT_NAME IS '客户端名称';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CALLBACK_URL IS '回调地址';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.AUTH_FLG IS '身份标识';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.UPDATE_TIME IS '更新时间';

CREATE TABLE WCDK_PROCESS_CLIENT_PROCESS (
    ID BIGINT NOT NULL,
    CLIENT_ID VARCHAR(64) NOT NULL,
    PROCESS_BEAN_NAME VARCHAR(128),
    PROCESS_DEFINITION_ID VARCHAR(128),
    PROCESS_NAME VARCHAR(255),
    EXCUTE_PARAM VARCHAR(1000),
    CREATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_CLIENT_PROCESS PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_CLIENT_PROCESS IS '客户端流程绑定表';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.CLIENT_ID IS '客户端标识';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.PROCESS_BEAN_NAME IS '流程处理器名称';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.PROCESS_DEFINITION_ID IS '流程定义ID';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.PROCESS_NAME IS '回调bean 处理器 ';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.EXCUTE_PARAM IS '执行参数';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.CREATE_TIME IS '创建时间';

CREATE UNIQUE INDEX UK_WCDK_PROCESS_CLIENT_ID ON WCDK_PROCESS_CLIENT(CLIENT_ID);
CREATE INDEX IDX_WCDK_PROCESS_CLIENT_PROCESS_CLIENT ON WCDK_PROCESS_CLIENT_PROCESS(CLIENT_ID);
CREATE INDEX IDX_WCDK_PROCESS_CLIENT_PROCESS_DEF ON WCDK_PROCESS_CLIENT_PROCESS(PROCESS_DEFINITION_ID);
CREATE UNIQUE INDEX UK_WCDK_PROCESS_CLIENT_PROCESS_DEF ON WCDK_PROCESS_CLIENT_PROCESS(CLIENT_ID, PROCESS_DEFINITION_ID);

CREATE TABLE SYS_DEPT (
    ID BIGINT NOT NULL,
    PARENT_ID BIGINT,
    DEPT_CODE VARCHAR(64) NOT NULL,
    DEPT_NAME VARCHAR(128) NOT NULL,
    SORT_NO INT DEFAULT 0,
    STATUS INT DEFAULT 1,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_DEPT PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_DEPT IS '部门表';
COMMENT ON COLUMN SYS_DEPT.ID IS '主键';
COMMENT ON COLUMN SYS_DEPT.PARENT_ID IS '上级部门ID';
COMMENT ON COLUMN SYS_DEPT.DEPT_CODE IS '部门编码';
COMMENT ON COLUMN SYS_DEPT.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN SYS_DEPT.SORT_NO IS '排序号';
COMMENT ON COLUMN SYS_DEPT.STATUS IS '状态';
COMMENT ON COLUMN SYS_DEPT.REMARK IS '备注';
COMMENT ON COLUMN SYS_DEPT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_DEPT.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_USER (
    ID BIGINT NOT NULL,
    DEPT_ID BIGINT,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD_HASH VARCHAR(64) NOT NULL,
    REAL_NAME VARCHAR(64) NOT NULL,
    MOBILE VARCHAR(32),
    EMAIL VARCHAR(128),
    STATUS INT DEFAULT 1,
    LAST_LOGIN_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_USER PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_USER IS '用户表';
COMMENT ON COLUMN SYS_USER.ID IS '主键';
COMMENT ON COLUMN SYS_USER.DEPT_ID IS '所属部门ID';
COMMENT ON COLUMN SYS_USER.USERNAME IS '用户名';
COMMENT ON COLUMN SYS_USER.PASSWORD_HASH IS '密码摘要';
COMMENT ON COLUMN SYS_USER.REAL_NAME IS '姓名';
COMMENT ON COLUMN SYS_USER.MOBILE IS '手机号';
COMMENT ON COLUMN SYS_USER.EMAIL IS '邮箱';
COMMENT ON COLUMN SYS_USER.STATUS IS '状态';
COMMENT ON COLUMN SYS_USER.LAST_LOGIN_TIME IS '最后登录时间';
COMMENT ON COLUMN SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_USER.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_ROLE (
    ID BIGINT NOT NULL,
    ROLE_CODE VARCHAR(64) NOT NULL,
    ROLE_NAME VARCHAR(64) NOT NULL,
    SORT_NO INT DEFAULT 0,
    STATUS INT DEFAULT 1,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_ROLE PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_ROLE IS '角色表';
COMMENT ON COLUMN SYS_ROLE.ID IS '主键';
COMMENT ON COLUMN SYS_ROLE.ROLE_CODE IS '角色编码';
COMMENT ON COLUMN SYS_ROLE.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN SYS_ROLE.SORT_NO IS '排序号';
COMMENT ON COLUMN SYS_ROLE.STATUS IS '状态';
COMMENT ON COLUMN SYS_ROLE.REMARK IS '备注';
COMMENT ON COLUMN SYS_ROLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ROLE.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_PERMISSION (
    ID BIGINT NOT NULL,
    PARENT_ID BIGINT,
    PERMISSION_CODE VARCHAR(128) NOT NULL,
    PERMISSION_NAME VARCHAR(128) NOT NULL,
    PERMISSION_TYPE VARCHAR(32),
    ROUTE_PATH VARCHAR(255),
    SORT_NO INT DEFAULT 0,
    STATUS INT DEFAULT 1,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_PERMISSION PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_PERMISSION IS '权限表';
COMMENT ON COLUMN SYS_PERMISSION.ID IS '主键';
COMMENT ON COLUMN SYS_PERMISSION.PARENT_ID IS '上级权限ID';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_CODE IS '权限编码';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_NAME IS '权限名称';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_TYPE IS '权限类型';
COMMENT ON COLUMN SYS_PERMISSION.ROUTE_PATH IS '路由地址';
COMMENT ON COLUMN SYS_PERMISSION.SORT_NO IS '排序号';
COMMENT ON COLUMN SYS_PERMISSION.STATUS IS '状态';
COMMENT ON COLUMN SYS_PERMISSION.REMARK IS '备注';
COMMENT ON COLUMN SYS_PERMISSION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_PERMISSION.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID)
);

COMMENT ON TABLE SYS_USER_ROLE IS '用户角色关联表';
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_USER_ROLE.CREATE_TIME IS '创建时间';

CREATE TABLE SYS_ROLE_PERMISSION (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_ROLE_PERMISSION PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

COMMENT ON TABLE SYS_ROLE_PERMISSION IS '角色权限关联表';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.PERMISSION_ID IS '权限ID';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.CREATE_TIME IS '创建时间';

CREATE UNIQUE INDEX UK_SYS_DEPT_CODE ON SYS_DEPT(DEPT_CODE);
CREATE UNIQUE INDEX UK_SYS_USER_USERNAME ON SYS_USER(USERNAME);
CREATE UNIQUE INDEX UK_SYS_ROLE_CODE ON SYS_ROLE(ROLE_CODE);
CREATE UNIQUE INDEX UK_SYS_PERMISSION_CODE ON SYS_PERMISSION(PERMISSION_CODE);

INSERT INTO SYS_DEPT (ID, PARENT_ID, DEPT_CODE, DEPT_NAME, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES (1001, NULL, 'HEAD', '总部', 1, 1, '默认根部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_ROLE (ID, ROLE_CODE, ROLE_NAME, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES (1001, 'ADMIN', '系统管理员', 1, 1, '默认管理员角色', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_USER (ID, DEPT_ID, USERNAME, PASSWORD_HASH, REAL_NAME, MOBILE, EMAIL, STATUS, LAST_LOGIN_TIME, CREATE_TIME, UPDATE_TIME)
VALUES (1001, 1001, 'admin', '0192023A7BBD73250516F069DF18B500', '系统管理员', NULL, NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1101, NULL, 'menu:home', '首页菜单', 'MENU', '/home', 1, 1, '首页菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1102, NULL, 'menu:deploy', '部署中心菜单', 'MENU', '/deploy', 2, 1, '部署中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1103, NULL, 'menu:model', '模型中心菜单', 'MENU', '/model', 3, 1, '模型中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1104, NULL, 'menu:designer', '流程设计菜单', 'MENU', '/designer', 4, 1, '流程设计菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1105, NULL, 'menu:process', '流程中心菜单', 'MENU', '/process', 5, 1, '流程中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1106, NULL, 'menu:task', '任务中心菜单', 'MENU', '/task', 6, 1, '任务中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1107, NULL, 'menu:sys:user', '用户管理菜单', 'MENU', '/system/user', 7, 1, '用户管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1108, NULL, 'menu:sys:role', '角色管理菜单', 'MENU', '/system/role', 8, 1, '角色管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1109, NULL, 'menu:sys:permission', '权限管理菜单', 'MENU', '/system/permission', 9, 1, '权限管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1110, NULL, 'menu:sys:dept', '部门管理菜单', 'MENU', '/system/dept', 10, 1, '部门管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1111, NULL, 'sys:user:view', '查看用户', 'BUTTON', NULL, 11, 1, '用户查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1112, NULL, 'sys:user:add', '新增用户', 'BUTTON', NULL, 12, 1, '用户新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1113, NULL, 'sys:user:edit', '修改用户', 'BUTTON', NULL, 13, 1, '用户修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1114, NULL, 'sys:user:delete', '删除用户', 'BUTTON', NULL, 14, 1, '用户删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1115, NULL, 'sys:role:view', '查看角色', 'BUTTON', NULL, 15, 1, '角色查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1116, NULL, 'sys:role:add', '新增角色', 'BUTTON', NULL, 16, 1, '角色新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1117, NULL, 'sys:role:edit', '修改角色', 'BUTTON', NULL, 17, 1, '角色修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1118, NULL, 'sys:role:delete', '删除角色', 'BUTTON', NULL, 18, 1, '角色删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1119, NULL, 'sys:permission:view', '查看权限', 'BUTTON', NULL, 19, 1, '权限查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1120, NULL, 'sys:permission:add', '新增权限', 'BUTTON', NULL, 20, 1, '权限新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1121, NULL, 'sys:permission:edit', '修改权限', 'BUTTON', NULL, 21, 1, '权限修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1122, NULL, 'sys:permission:delete', '删除权限', 'BUTTON', NULL, 22, 1, '权限删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1123, NULL, 'sys:dept:view', '查看部门', 'BUTTON', NULL, 23, 1, '部门查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1124, NULL, 'sys:dept:add', '新增部门', 'BUTTON', NULL, 24, 1, '部门新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1125, NULL, 'sys:dept:edit', '修改部门', 'BUTTON', NULL, 25, 1, '部门修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1126, NULL, 'sys:dept:delete', '删除部门', 'BUTTON', NULL, 26, 1, '部门删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1127, NULL, '*:*:*', '系统全量权限', 'BUTTON', NULL, 99, 1, '管理员全量权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1128, NULL, 'client:view', '客户端管理菜单', 'MENU', '/client', 27, 1, '查看已注册客户端信息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1129, NULL, 'client:delete', '移除客户端', 'BUTTON', NULL, 28, 1, '移除客户端注册信息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID, CREATE_TIME)
VALUES (1001, 1001, CURRENT_TIMESTAMP);

INSERT INTO SYS_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, CREATE_TIME)
SELECT 1001, ID, CURRENT_TIMESTAMP FROM SYS_PERMISSION;
