CREATE TABLE `WCDK_PROCESS_REQUEST` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `PROCESS_NO` VARCHAR(64) NOT NULL COMMENT '流程申请编号',
    `STARTER` VARCHAR(64) NOT NULL COMMENT '流程发起人',
    `TASK_NAME` VARCHAR(255) NOT NULL COMMENT '任务名称',
    `BUSINESS_TITLE` VARCHAR(1000) NOT NULL COMMENT '业务标题',
    `FORM_DATA_JSON` TEXT COMMENT '动态表单数据JSON',
    `STATUS` VARCHAR(32) NOT NULL COMMENT '流程申请状态',
    `PROCESS_INSTANCE_ID` VARCHAR(64) DEFAULT NULL COMMENT '流程实例ID',
    `CURRENT_TASK_ID` VARCHAR(64) DEFAULT NULL COMMENT '当前任务ID',
    `CURRENT_TASK_NAME` VARCHAR(128) DEFAULT NULL COMMENT '当前任务名称',
    `PROCESS_DEFINITION_KEY` VARCHAR(128) NOT NULL COMMENT '流程定义标识',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_WCDK_PROCESS_REQUEST_NO` (`PROCESS_NO`),
    KEY `IDX_WCDK_PROCESS_REQUEST_PROC` (`PROCESS_INSTANCE_ID`),
    KEY `IDX_WCDK_PROCESS_REQUEST_DEF_KEY` (`PROCESS_DEFINITION_KEY`),
    KEY `IDX_WCDK_PROCESS_REQUEST_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流程申请业务表';

CREATE TABLE `WCDK_PROCESS_CLIENT` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `CLIENT_ID` VARCHAR(64) NOT NULL COMMENT '客户端标识',
    `CLIENT_NAME` VARCHAR(128) NOT NULL COMMENT '客户端名称',
    `CALLBACK_URL` VARCHAR(500) DEFAULT NULL COMMENT '回调地址',
    `AUTH_FLG` TEXT COMMENT '身份标识',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_WCDK_PROCESS_CLIENT_ID` (`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='客户端回调绑定表';

CREATE TABLE `WCDK_PROCESS_CLIENT_PROCESS` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `CLIENT_ID` VARCHAR(64) NOT NULL COMMENT '客户端标识',
    `PROCESS_BEAN_NAME` VARCHAR(128) DEFAULT NULL COMMENT '流程处理器名称',
    `PROCESS_DEFINITION_ID` VARCHAR(128) DEFAULT NULL COMMENT '流程定义ID',
    `PROCESS_NAME` VARCHAR(255) DEFAULT NULL COMMENT '回调bean 处理器',
    `EXCUTE_PARAM` VARCHAR(1000) DEFAULT NULL COMMENT '执行参数',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_WCDK_PROCESS_CLIENT_PROCESS_DEF` (`CLIENT_ID`, `PROCESS_DEFINITION_ID`),
    KEY `IDX_WCDK_PROCESS_CLIENT_PROCESS_CLIENT` (`CLIENT_ID`),
    KEY `IDX_WCDK_PROCESS_CLIENT_PROCESS_DEF` (`PROCESS_DEFINITION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='客户端流程绑定表';

CREATE TABLE `SYS_DEPT` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `PARENT_ID` BIGINT DEFAULT NULL COMMENT '上级部门ID',
    `DEPT_CODE` VARCHAR(64) NOT NULL COMMENT '部门编码',
    `DEPT_NAME` VARCHAR(128) NOT NULL COMMENT '部门名称',
    `SORT_NO` INT DEFAULT 0 COMMENT '排序号',
    `STATUS` INT DEFAULT 1 COMMENT '状态',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SYS_DEPT_CODE` (`DEPT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='部门表';

CREATE TABLE `SYS_USER` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `DEPT_ID` BIGINT DEFAULT NULL COMMENT '所属部门ID',
    `USERNAME` VARCHAR(64) NOT NULL COMMENT '用户名',
    `PASSWORD_HASH` VARCHAR(64) NOT NULL COMMENT '密码摘要',
    `REAL_NAME` VARCHAR(64) NOT NULL COMMENT '姓名',
    `MOBILE` VARCHAR(32) DEFAULT NULL COMMENT '手机号',
    `EMAIL` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
    `STATUS` INT DEFAULT 1 COMMENT '状态',
    `LAST_LOGIN_TIME` DATETIME DEFAULT NULL COMMENT '最后登录时间',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SYS_USER_USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';

CREATE TABLE `SYS_ROLE` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `ROLE_CODE` VARCHAR(64) NOT NULL COMMENT '角色编码',
    `ROLE_NAME` VARCHAR(64) NOT NULL COMMENT '角色名称',
    `SORT_NO` INT DEFAULT 0 COMMENT '排序号',
    `STATUS` INT DEFAULT 1 COMMENT '状态',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SYS_ROLE_CODE` (`ROLE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色表';

CREATE TABLE `SYS_PERMISSION` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `PARENT_ID` BIGINT DEFAULT NULL COMMENT '上级权限ID',
    `PERMISSION_CODE` VARCHAR(128) NOT NULL COMMENT '权限编码',
    `PERMISSION_NAME` VARCHAR(128) NOT NULL COMMENT '权限名称',
    `PERMISSION_TYPE` VARCHAR(32) DEFAULT NULL COMMENT '权限类型',
    `ROUTE_PATH` VARCHAR(255) DEFAULT NULL COMMENT '路由地址',
    `ICON` VARCHAR(128) DEFAULT NULL COMMENT '图标',
    `SORT_NO` INT DEFAULT 0 COMMENT '排序号',
    `STATUS` INT DEFAULT 1 COMMENT '状态',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SYS_PERMISSION_CODE` (`PERMISSION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='权限表';

CREATE TABLE `SYS_USER_ROLE` (
    `USER_ID` BIGINT NOT NULL COMMENT '用户ID',
    `ROLE_ID` BIGINT NOT NULL COMMENT '角色ID',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`USER_ID`, `ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户角色关联表';

CREATE TABLE `SYS_ROLE_PERMISSION` (
    `ROLE_ID` BIGINT NOT NULL COMMENT '角色ID',
    `PERMISSION_ID` BIGINT NOT NULL COMMENT '权限ID',
    `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (`ROLE_ID`, `PERMISSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色权限关联表';

INSERT INTO `SYS_DEPT` (`ID`, `PARENT_ID`, `DEPT_CODE`, `DEPT_NAME`, `SORT_NO`, `STATUS`, `REMARK`, `CREATE_TIME`, `UPDATE_TIME`)
VALUES (1001, NULL, 'HEAD', '总部', 1, 1, '默认根部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `SYS_ROLE` (`ID`, `ROLE_CODE`, `ROLE_NAME`, `SORT_NO`, `STATUS`, `REMARK`, `CREATE_TIME`, `UPDATE_TIME`)
VALUES (1001, 'ADMIN', '系统管理员', 1, 1, '默认管理员角色', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `SYS_USER` (`ID`, `DEPT_ID`, `USERNAME`, `PASSWORD_HASH`, `REAL_NAME`, `MOBILE`, `EMAIL`, `STATUS`, `LAST_LOGIN_TIME`, `CREATE_TIME`, `UPDATE_TIME`)
VALUES (1001, 1001, 'admin', '0192023A7BBD73250516F069DF18B500', '系统管理员', NULL, NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `SYS_PERMISSION` (`ID`, `PARENT_ID`, `PERMISSION_CODE`, `PERMISSION_NAME`, `PERMISSION_TYPE`, `ROUTE_PATH`, `SORT_NO`, `STATUS`, `REMARK`, `CREATE_TIME`, `UPDATE_TIME`) VALUES
(1101, NULL, 'menu:home', '首页菜单', 'MENU', '/home', 1, 1, '首页菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1102, NULL, 'menu:deploy', '部署中心菜单', 'MENU', '/deploy', 2, 1, '部署中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1103, NULL, 'menu:model', '模型中心菜单', 'MENU', '/model', 3, 1, '模型中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1104, NULL, 'menu:designer', '流程设计菜单', 'MENU', '/designer', 4, 1, '流程设计菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1105, NULL, 'menu:process', '流程中心菜单', 'MENU', '/process', 5, 1, '流程中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1106, NULL, 'menu:task', '任务中心菜单', 'MENU', '/task', 6, 1, '任务中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1107, NULL, 'menu:sys:user', '用户管理菜单', 'MENU', '/system/user', 7, 1, '用户管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1108, NULL, 'menu:sys:role', '角色管理菜单', 'MENU', '/system/role', 8, 1, '角色管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1109, NULL, 'menu:sys:permission', '权限管理菜单', 'MENU', '/system/permission', 9, 1, '权限管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1110, NULL, 'menu:sys:dept', '部门管理菜单', 'MENU', '/system/dept', 10, 1, '部门管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1111, NULL, 'sys:user:view', '查看用户', 'BUTTON', NULL, 11, 1, '用户查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1112, NULL, 'sys:user:add', '新增用户', 'BUTTON', NULL, 12, 1, '用户新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1113, NULL, 'sys:user:edit', '修改用户', 'BUTTON', NULL, 13, 1, '用户修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1114, NULL, 'sys:user:delete', '删除用户', 'BUTTON', NULL, 14, 1, '用户删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1115, NULL, 'sys:role:view', '查看角色', 'BUTTON', NULL, 15, 1, '角色查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1116, NULL, 'sys:role:add', '新增角色', 'BUTTON', NULL, 16, 1, '角色新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1117, NULL, 'sys:role:edit', '修改角色', 'BUTTON', NULL, 17, 1, '角色修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1118, NULL, 'sys:role:delete', '删除角色', 'BUTTON', NULL, 18, 1, '角色删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1119, NULL, 'sys:permission:view', '查看权限', 'BUTTON', NULL, 19, 1, '权限查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1120, NULL, 'sys:permission:add', '新增权限', 'BUTTON', NULL, 20, 1, '权限新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1121, NULL, 'sys:permission:edit', '修改权限', 'BUTTON', NULL, 21, 1, '权限修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1122, NULL, 'sys:permission:delete', '删除权限', 'BUTTON', NULL, 22, 1, '权限删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1123, NULL, 'sys:dept:view', '查看部门', 'BUTTON', NULL, 23, 1, '部门查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1124, NULL, 'sys:dept:add', '新增部门', 'BUTTON', NULL, 24, 1, '部门新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1125, NULL, 'sys:dept:edit', '修改部门', 'BUTTON', NULL, 25, 1, '部门修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1126, NULL, 'sys:dept:delete', '删除部门', 'BUTTON', NULL, 26, 1, '部门删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1127, NULL, '*:*:*', '系统全量权限', 'BUTTON', NULL, 99, 1, '管理员全量权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `SYS_PERMISSION` (`ID`, `PARENT_ID`, `PERMISSION_CODE`, `PERMISSION_NAME`, `PERMISSION_TYPE`, `ROUTE_PATH`, `SORT_NO`, `STATUS`, `REMARK`, `CREATE_TIME`, `UPDATE_TIME`) VALUES
(1128, NULL, 'client:view', '客户端管理菜单', 'MENU', '/client', 27, 1, '查看已注册客户端信息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `SYS_PERMISSION` (`ID`, `PARENT_ID`, `PERMISSION_CODE`, `PERMISSION_NAME`, `PERMISSION_TYPE`, `ROUTE_PATH`, `SORT_NO`, `STATUS`, `REMARK`, `CREATE_TIME`, `UPDATE_TIME`) VALUES
(1129, NULL, 'client:delete', '移除客户端', 'BUTTON', NULL, 28, 1, '移除客户端注册信息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-house' WHERE `PERMISSION_CODE` = 'menu:home';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-upload2' WHERE `PERMISSION_CODE` = 'menu:deploy';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-collection' WHERE `PERMISSION_CODE` = 'menu:model';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-edit-outline' WHERE `PERMISSION_CODE` = 'menu:designer';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-s-operation' WHERE `PERMISSION_CODE` = 'menu:process';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-s-check' WHERE `PERMISSION_CODE` = 'menu:task';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-connection' WHERE `PERMISSION_CODE` = 'client:view';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-user' WHERE `PERMISSION_CODE` = 'menu:sys:user';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-s-custom' WHERE `PERMISSION_CODE` = 'menu:sys:role';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-key' WHERE `PERMISSION_CODE` = 'menu:sys:permission';
UPDATE `SYS_PERMISSION` SET `ICON` = 'el-icon-office-building' WHERE `PERMISSION_CODE` = 'menu:sys:dept';

INSERT INTO `SYS_PERMISSION` (`ID`, `PARENT_ID`, `PERMISSION_CODE`, `PERMISSION_NAME`, `PERMISSION_TYPE`, `ROUTE_PATH`, `SORT_NO`, `STATUS`, `REMARK`, `CREATE_TIME`, `UPDATE_TIME`) VALUES
(1130, 1102, 'deploy:tab:create', '创建部署标签页', 'TAB', NULL, 1, 1, '部署中心创建部署标签页', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1131, 1102, 'deploy:tab:list', '流程列表标签页', 'TAB', NULL, 2, 1, '部署中心流程列表标签页', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1132, 1103, 'model:tab:create', '创建模型标签页', 'TAB', NULL, 1, 1, '模型中心创建模型标签页', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1133, 1103, 'model:tab:list', '模型列表标签页', 'TAB', NULL, 2, 1, '模型中心模型列表标签页', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1134, 1105, 'process:tab:create', '创建流程标签页', 'TAB', NULL, 1, 1, '流程中心创建流程标签页', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1135, 1105, 'process:tab:list', '流程列表标签页', 'TAB', NULL, 2, 1, '流程中心流程列表标签页', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1136, 1102, 'deploy:refresh', '刷新部署', 'BUTTON', NULL, 10, 1, '刷新部署中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1137, 1102, 'deploy:create', '提交部署', 'BUTTON', NULL, 11, 1, '提交流程部署', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1138, 1102, 'deploy:start', '发起审批', 'BUTTON', NULL, 12, 1, '从部署发起审批', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1139, 1102, 'deploy:edit', '编辑部署', 'BUTTON', NULL, 13, 1, '编辑部署流程定义', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1140, 1102, 'deploy:view', '查看部署', 'BUTTON', NULL, 14, 1, '查看部署详情', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1141, 1102, 'deploy:preview', '预览部署', 'BUTTON', NULL, 15, 1, '预览部署流程图', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1142, 1102, 'deploy:binding', '修改部署绑定', 'BUTTON', NULL, 16, 1, '修改部署客户端绑定', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1143, 1102, 'deploy:delete', '删除部署', 'BUTTON', NULL, 17, 1, '删除部署数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1144, 1103, 'model:refresh', '刷新模型', 'BUTTON', NULL, 10, 1, '刷新模型中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1145, 1103, 'model:create', '创建模型', 'BUTTON', NULL, 11, 1, '创建流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1146, 1103, 'model:edit', '修改模型', 'BUTTON', NULL, 12, 1, '修改流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1147, 1103, 'model:preview', '预览模型', 'BUTTON', NULL, 13, 1, '预览流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1148, 1103, 'model:deploy', '部署模型', 'BUTTON', NULL, 14, 1, '部署流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1149, 1103, 'model:delete', '删除模型', 'BUTTON', NULL, 15, 1, '删除流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1150, 1105, 'process:refresh', '刷新流程', 'BUTTON', NULL, 10, 1, '刷新流程中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1151, 1105, 'process:view', '查看流程', 'BUTTON', NULL, 11, 1, '查看流程详情', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1152, 1105, 'process:submit', '提交流程', 'BUTTON', NULL, 12, 1, '提交草稿流程', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1153, 1105, 'process:delete', '删除流程', 'BUTTON', NULL, 13, 1, '删除流程申请', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1154, 1105, 'process:action:draft', '保存草稿', 'BUTTON', NULL, 14, 1, '流程表单保存草稿按钮', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1155, 1105, 'process:action:submit', '提交申请', 'BUTTON', NULL, 15, 1, '流程表单提交申请按钮', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1156, 1105, 'process:action:reset', '重置流程表单', 'BUTTON', NULL, 16, 1, '流程表单重置按钮', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1157, 1106, 'task:refresh', '刷新任务', 'BUTTON', NULL, 10, 1, '刷新任务中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1158, 1106, 'task:view', '查看任务', 'BUTTON', NULL, 11, 1, '查看任务流程图', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1159, 1106, 'task:approve', '办理任务', 'BUTTON', NULL, 12, 1, '办理审批任务', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1160, 1106, 'task:delete', '删除任务', 'BUTTON', NULL, 13, 1, '删除任务', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1161, 1128, 'client:refresh', '刷新客户端', 'BUTTON', NULL, 10, 1, '刷新客户端数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1162, 1128, 'client:detect', '检测客户端', 'BUTTON', NULL, 11, 1, '检测客户端存活状态', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1163, 1105, 'process:status:tag', '流程状态标签', 'TAG', NULL, 30, 1, '流程中心状态标签资源', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO `SYS_USER_ROLE` (`USER_ID`, `ROLE_ID`, `CREATE_TIME`)
VALUES (1001, 1001, CURRENT_TIMESTAMP);

INSERT INTO `SYS_ROLE_PERMISSION` (`ROLE_ID`, `PERMISSION_ID`, `CREATE_TIME`)
SELECT 1001, `ID`, CURRENT_TIMESTAMP FROM `SYS_PERMISSION`;
