CREATE TABLE WCDK_PROCESS_REQUEST (
    ID BIGINT NOT NULL,
    PROCESS_NO VARCHAR(64) NOT NULL,
    STARTER VARCHAR(64) NOT NULL,
    TASK_NAME VARCHAR(255) NOT NULL,
    BUSINESS_TITLE VARCHAR(1000) NOT NULL,
    FORM_DATA_JSON CLOB,
    STATUS VARCHAR(32) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64),
    CURRENT_TASK_ID VARCHAR(64),
    CURRENT_TASK_NAME VARCHAR(128),
    PROCESS_DEFINITION_KEY VARCHAR(128) NOT NULL,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_REQUEST PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_REQUEST IS '流程申请业务表';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_NO IS '流程申请编号';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.STARTER IS '流程发起人';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.TASK_NAME IS '任务名称';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.BUSINESS_TITLE IS '业务标题';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.FORM_DATA_JSON IS '动态表单数据JSON';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.STATUS IS '流程申请状态';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_INSTANCE_ID IS '流程实例ID';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CURRENT_TASK_ID IS '当前任务ID';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CURRENT_TASK_NAME IS '当前任务名称';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_DEFINITION_KEY IS '流程定义标识';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.UPDATE_TIME IS '更新时间';

CREATE UNIQUE INDEX UK_WCDK_PROCESS_REQUEST_NO ON WCDK_PROCESS_REQUEST(PROCESS_NO);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_PROC ON WCDK_PROCESS_REQUEST(PROCESS_INSTANCE_ID);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_DEF_KEY ON WCDK_PROCESS_REQUEST(PROCESS_DEFINITION_KEY);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_STATUS ON WCDK_PROCESS_REQUEST(STATUS);

CREATE TABLE WCDK_PROCESS_CLIENT (
    ID BIGINT NOT NULL,
    CLIENT_ID VARCHAR(64) NOT NULL,
    CLIENT_NAME VARCHAR(128) NOT NULL,
    CALLBACK_URL VARCHAR(500),
    SERVICE_NAME VARCHAR(128),
    AUTH_FLG CLOB,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_CLIENT PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_CLIENT IS '客户端回调绑定表';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CLIENT_ID IS '客户端标识';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CLIENT_NAME IS '客户端名称';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CALLBACK_URL IS '回调地址';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.SERVICE_NAME IS '注册中心服务名';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.AUTH_FLG IS '身份标识';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT.UPDATE_TIME IS '更新时间';

CREATE TABLE WCDK_PROCESS_CLIENT_PROCESS (
    ID BIGINT NOT NULL,
    CLIENT_ID VARCHAR(64) NOT NULL,
    PROCESS_BEAN_NAME VARCHAR(128),
    PROCESS_DEFINITION_ID VARCHAR(128),
    PROCESS_NAME VARCHAR(255),
    EXCUTE_PARAM VARCHAR(1000),
    CREATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_CLIENT_PROCESS PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_CLIENT_PROCESS IS '客户端流程绑定表';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.CLIENT_ID IS '客户端标识';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.PROCESS_BEAN_NAME IS '流程处理器名称';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.PROCESS_DEFINITION_ID IS '流程定义ID';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.PROCESS_NAME IS '回调bean 处理器 ';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.EXCUTE_PARAM IS '执行参数';
COMMENT ON COLUMN WCDK_PROCESS_CLIENT_PROCESS.CREATE_TIME IS '创建时间';

CREATE UNIQUE INDEX UK_WCDK_PROCESS_CLIENT_ID ON WCDK_PROCESS_CLIENT(CLIENT_ID);
CREATE INDEX IDX_WCDK_PROCESS_CLIENT_PROCESS_CLIENT ON WCDK_PROCESS_CLIENT_PROCESS(CLIENT_ID);
CREATE INDEX IDX_WCDK_PROCESS_CLIENT_PROCESS_DEF ON WCDK_PROCESS_CLIENT_PROCESS(PROCESS_DEFINITION_ID);
CREATE UNIQUE INDEX UK_WCDK_PROCESS_CLIENT_PROCESS_DEF ON WCDK_PROCESS_CLIENT_PROCESS(CLIENT_ID, PROCESS_DEFINITION_ID);

CREATE TABLE WCDK_PROCESS_DEFINITION_META (
    ID BIGINT NOT NULL,
    PROCESS_DEFINITION_ID VARCHAR(128) NOT NULL,
    PROCESS_DEFINITION_KEY VARCHAR(128),
    PROCESS_DEFINITION_VERSION INT,
    DEPLOYMENT_ID VARCHAR(128),
    INVALID_STATUS INT DEFAULT 0 NOT NULL,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_DEFINITION_META PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_DEFINITION_META IS '流程定义元数据表';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.PROCESS_DEFINITION_ID IS 'Flowable流程定义ID';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.PROCESS_DEFINITION_KEY IS 'Flowable流程定义KEY';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.PROCESS_DEFINITION_VERSION IS 'Flowable流程定义版本';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.DEPLOYMENT_ID IS 'Flowable部署ID';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.INVALID_STATUS IS '作废状态：0生效，1已作废';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_DEFINITION_META.UPDATE_TIME IS '更新时间';

CREATE UNIQUE INDEX UK_WCDK_PROCESS_DEFINITION_META_DEF ON WCDK_PROCESS_DEFINITION_META(PROCESS_DEFINITION_ID);
CREATE INDEX IDX_WCDK_PROCESS_DEFINITION_META_KEY ON WCDK_PROCESS_DEFINITION_META(PROCESS_DEFINITION_KEY);
CREATE INDEX IDX_WCDK_PROCESS_DEFINITION_META_DEPLOY ON WCDK_PROCESS_DEFINITION_META(DEPLOYMENT_ID);
CREATE INDEX IDX_WCDK_PROCESS_DEFINITION_META_INVALID ON WCDK_PROCESS_DEFINITION_META(INVALID_STATUS);

CREATE TABLE WCDK_PROCESS_FORM (
    ID BIGINT NOT NULL,
    FORM_KEY VARCHAR(128) NOT NULL,
    FORM_NAME VARCHAR(255) NOT NULL,
    FORM_VERSION INT DEFAULT 1 NOT NULL,
    FORM_SCHEMA_JSON CLOB NOT NULL,
    RESOURCE_NAME VARCHAR(255),
    TENANT_ID VARCHAR(128) DEFAULT '' NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    REMARK VARCHAR(500),
    CREATE_USER VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_FORM PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_FORM IS '流程表单定义表';
COMMENT ON COLUMN WCDK_PROCESS_FORM.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_FORM.FORM_KEY IS '表单标识，对应Flowable表单key';
COMMENT ON COLUMN WCDK_PROCESS_FORM.FORM_NAME IS '表单名称';
COMMENT ON COLUMN WCDK_PROCESS_FORM.FORM_VERSION IS '表单版本';
COMMENT ON COLUMN WCDK_PROCESS_FORM.FORM_SCHEMA_JSON IS '表单设计JSON';
COMMENT ON COLUMN WCDK_PROCESS_FORM.RESOURCE_NAME IS '表单资源名称';
COMMENT ON COLUMN WCDK_PROCESS_FORM.TENANT_ID IS '租户ID';
COMMENT ON COLUMN WCDK_PROCESS_FORM.STATUS IS '状态：1启用，0停用';
COMMENT ON COLUMN WCDK_PROCESS_FORM.REMARK IS '备注';
COMMENT ON COLUMN WCDK_PROCESS_FORM.CREATE_USER IS '创建人';
COMMENT ON COLUMN WCDK_PROCESS_FORM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_FORM.UPDATE_TIME IS '更新时间';

CREATE UNIQUE INDEX UK_WCDK_PROCESS_FORM_KEY_VER ON WCDK_PROCESS_FORM(FORM_KEY, FORM_VERSION, TENANT_ID);
CREATE INDEX IDX_WCDK_PROCESS_FORM_KEY ON WCDK_PROCESS_FORM(FORM_KEY);
CREATE INDEX IDX_WCDK_PROCESS_FORM_STATUS ON WCDK_PROCESS_FORM(STATUS);

CREATE TABLE WCDK_PROCESS_FORM_BINDING (
    ID BIGINT NOT NULL,
    FORM_ID BIGINT NOT NULL,
    PROCESS_DEFINITION_ID VARCHAR(128),
    PROCESS_DEFINITION_KEY VARCHAR(128) NOT NULL,
    PROCESS_DEFINITION_VERSION INT,
    DEPLOYMENT_ID VARCHAR(128),
    TENANT_ID VARCHAR(128) DEFAULT '' NOT NULL,
    BIND_SCOPE VARCHAR(32) DEFAULT 'PROCESS' NOT NULL,
    TASK_DEFINITION_KEY VARCHAR(128) DEFAULT '' NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_FORM_BINDING PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_FORM_BINDING IS '流程表单绑定表';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.FORM_ID IS '表单ID';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.PROCESS_DEFINITION_ID IS 'Flowable流程定义ID';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.PROCESS_DEFINITION_KEY IS 'Flowable流程定义KEY';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.PROCESS_DEFINITION_VERSION IS 'Flowable流程定义版本';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.DEPLOYMENT_ID IS 'Flowable部署ID';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.TENANT_ID IS '租户ID';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.BIND_SCOPE IS '绑定范围：PROCESS流程，START发起，TASK任务';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.TASK_DEFINITION_KEY IS '任务定义KEY，流程级绑定为空字符串';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.STATUS IS '状态：1启用，0停用';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.REMARK IS '备注';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_FORM_BINDING.UPDATE_TIME IS '更新时间';

CREATE INDEX IDX_WCDK_PROCESS_FORM_BINDING_FORM ON WCDK_PROCESS_FORM_BINDING(FORM_ID);
CREATE INDEX IDX_WCDK_PROCESS_FORM_BINDING_DEF_ID ON WCDK_PROCESS_FORM_BINDING(PROCESS_DEFINITION_ID);
CREATE INDEX IDX_WCDK_PROCESS_FORM_BINDING_DEF_KEY ON WCDK_PROCESS_FORM_BINDING(PROCESS_DEFINITION_KEY);
CREATE INDEX IDX_WCDK_PROCESS_FORM_BINDING_DEPLOY ON WCDK_PROCESS_FORM_BINDING(DEPLOYMENT_ID);
CREATE UNIQUE INDEX UK_WCDK_PROCESS_FORM_BINDING_DEF ON WCDK_PROCESS_FORM_BINDING(FORM_ID, PROCESS_DEFINITION_ID, BIND_SCOPE, TASK_DEFINITION_KEY, TENANT_ID);

CREATE TABLE SYS_DEPT (
    ID BIGINT NOT NULL,
    PARENT_ID BIGINT,
    DEPT_CODE VARCHAR(64) NOT NULL,
    DEPT_NAME VARCHAR(128) NOT NULL,
    SORT_NO INT DEFAULT 0,
    STATUS INT DEFAULT 1,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_DEPT PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_DEPT IS '部门表';
COMMENT ON COLUMN SYS_DEPT.ID IS '主键';
COMMENT ON COLUMN SYS_DEPT.PARENT_ID IS '上级部门ID';
COMMENT ON COLUMN SYS_DEPT.DEPT_CODE IS '部门编码';
COMMENT ON COLUMN SYS_DEPT.DEPT_NAME IS '部门名称';
COMMENT ON COLUMN SYS_DEPT.SORT_NO IS '排序号';
COMMENT ON COLUMN SYS_DEPT.STATUS IS '状态';
COMMENT ON COLUMN SYS_DEPT.REMARK IS '备注';
COMMENT ON COLUMN SYS_DEPT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_DEPT.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_USER (
    ID BIGINT NOT NULL,
    DEPT_ID BIGINT,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD_HASH VARCHAR(64) NOT NULL,
    REAL_NAME VARCHAR(64) NOT NULL,
    MOBILE VARCHAR(32),
    EMAIL VARCHAR(128),
    STATUS INT DEFAULT 1,
    LAST_LOGIN_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_USER PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_USER IS '用户表';
COMMENT ON COLUMN SYS_USER.ID IS '主键';
COMMENT ON COLUMN SYS_USER.DEPT_ID IS '所属部门ID';
COMMENT ON COLUMN SYS_USER.USERNAME IS '用户名';
COMMENT ON COLUMN SYS_USER.PASSWORD_HASH IS '密码摘要';
COMMENT ON COLUMN SYS_USER.REAL_NAME IS '姓名';
COMMENT ON COLUMN SYS_USER.MOBILE IS '手机号';
COMMENT ON COLUMN SYS_USER.EMAIL IS '邮箱';
COMMENT ON COLUMN SYS_USER.STATUS IS '状态';
COMMENT ON COLUMN SYS_USER.LAST_LOGIN_TIME IS '最后登录时间';
COMMENT ON COLUMN SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_USER.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_ROLE (
    ID BIGINT NOT NULL,
    ROLE_CODE VARCHAR(64) NOT NULL,
    ROLE_NAME VARCHAR(64) NOT NULL,
    SORT_NO INT DEFAULT 0,
    STATUS INT DEFAULT 1,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_ROLE PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_ROLE IS '角色表';
COMMENT ON COLUMN SYS_ROLE.ID IS '主键';
COMMENT ON COLUMN SYS_ROLE.ROLE_CODE IS '角色编码';
COMMENT ON COLUMN SYS_ROLE.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN SYS_ROLE.SORT_NO IS '排序号';
COMMENT ON COLUMN SYS_ROLE.STATUS IS '状态';
COMMENT ON COLUMN SYS_ROLE.REMARK IS '备注';
COMMENT ON COLUMN SYS_ROLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_ROLE.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_PERMISSION (
    ID BIGINT NOT NULL,
    PARENT_ID BIGINT,
    PERMISSION_CODE VARCHAR(128) NOT NULL,
    PERMISSION_NAME VARCHAR(128) NOT NULL,
    PERMISSION_TYPE VARCHAR(32),
    ROUTE_PATH VARCHAR(255),
    ICON VARCHAR(128),
    SORT_NO INT DEFAULT 0,
    STATUS INT DEFAULT 1,
    REMARK VARCHAR(500),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_PERMISSION PRIMARY KEY (ID)
);

COMMENT ON TABLE SYS_PERMISSION IS '权限表';
COMMENT ON COLUMN SYS_PERMISSION.ID IS '主键';
COMMENT ON COLUMN SYS_PERMISSION.PARENT_ID IS '上级权限ID';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_CODE IS '权限编码';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_NAME IS '权限名称';
COMMENT ON COLUMN SYS_PERMISSION.PERMISSION_TYPE IS '权限类型';
COMMENT ON COLUMN SYS_PERMISSION.ROUTE_PATH IS '路由地址';
COMMENT ON COLUMN SYS_PERMISSION.ICON IS '图标';
COMMENT ON COLUMN SYS_PERMISSION.SORT_NO IS '排序号';
COMMENT ON COLUMN SYS_PERMISSION.STATUS IS '状态';
COMMENT ON COLUMN SYS_PERMISSION.REMARK IS '备注';
COMMENT ON COLUMN SYS_PERMISSION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_PERMISSION.UPDATE_TIME IS '更新时间';

CREATE TABLE SYS_USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID)
);

COMMENT ON TABLE SYS_USER_ROLE IS '用户角色关联表';
COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_USER_ROLE.CREATE_TIME IS '创建时间';

CREATE TABLE SYS_ROLE_PERMISSION (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP,
    CONSTRAINT PK_SYS_ROLE_PERMISSION PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

COMMENT ON TABLE SYS_ROLE_PERMISSION IS '角色权限关联表';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.PERMISSION_ID IS '权限ID';
COMMENT ON COLUMN SYS_ROLE_PERMISSION.CREATE_TIME IS '创建时间';

CREATE UNIQUE INDEX UK_SYS_DEPT_CODE ON SYS_DEPT(DEPT_CODE);
CREATE UNIQUE INDEX UK_SYS_USER_USERNAME ON SYS_USER(USERNAME);
CREATE UNIQUE INDEX UK_SYS_ROLE_CODE ON SYS_ROLE(ROLE_CODE);
CREATE UNIQUE INDEX UK_SYS_PERMISSION_CODE ON SYS_PERMISSION(PERMISSION_CODE);

INSERT INTO SYS_DEPT (ID, PARENT_ID, DEPT_CODE, DEPT_NAME, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES (1001, NULL, 'HEAD', '总部', 1, 1, '默认根部门', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_ROLE (ID, ROLE_CODE, ROLE_NAME, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME)
VALUES (1001, 'ADMIN', '系统管理员', 1, 1, '默认管理员角色', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_USER (ID, DEPT_ID, USERNAME, PASSWORD_HASH, REAL_NAME, MOBILE, EMAIL, STATUS, LAST_LOGIN_TIME, CREATE_TIME, UPDATE_TIME)
VALUES (1001, 1001, 'admin', '0192023A7BBD73250516F069DF18B500', '系统管理员', NULL, NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1101, NULL, 'menu:home', '首页', 'MENU', '/home', 1, 1, '首页菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1102, NULL, 'menu:deploy', '部署中心', 'MENU', '/deploy', 2, 1, '部署中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1103, NULL, 'menu:model', '模型中心', 'MENU', '/model', 3, 1, '模型中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1104, NULL, 'menu:designer', '流程设计', 'MENU', '/designer', 4, 1, '流程设计菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1170, NULL, 'menu:form', '表单设计', 'MENU', '/form-designer', 5, 1, '表单设计菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1105, NULL, 'menu:process', '流程中心', 'MENU', '/process', 5, 1, '流程中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1106, NULL, 'menu:task', '任务中心', 'MENU', '/task', 6, 1, '任务中心菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1107, NULL, 'menu:sys:user', '用户管理', 'MENU', '/system/user', 7, 1, '用户管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1108, NULL, 'menu:sys:role', '角色管理', 'MENU', '/system/role', 8, 1, '角色管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1109, NULL, 'menu:sys:permission', '权限管理', 'MENU', '/system/permission', 9, 1, '权限管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1110, NULL, 'menu:sys:dept', '部门管理', 'MENU', '/system/dept', 10, 1, '部门管理菜单权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1111, 1107, 'sys:user:view', '查看用户', 'BUTTON', NULL, 11, 1, '用户查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1112, 1107, 'sys:user:add', '新增用户', 'BUTTON', NULL, 12, 1, '用户新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1113, 1107, 'sys:user:edit', '修改用户', 'BUTTON', NULL, 13, 1, '用户修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1114, 1107, 'sys:user:delete', '删除用户', 'BUTTON', NULL, 14, 1, '用户删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1115, 1108, 'sys:role:view', '查看角色', 'BUTTON', NULL, 15, 1, '角色查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1116, 1108, 'sys:role:add', '新增角色', 'BUTTON', NULL, 16, 1, '角色新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1117, 1108, 'sys:role:edit', '修改角色', 'BUTTON', NULL, 17, 1, '角色修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1118, 1108, 'sys:role:delete', '删除角色', 'BUTTON', NULL, 18, 1, '角色删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1119, 1109, 'sys:permission:view', '查看权限', 'BUTTON', NULL, 19, 1, '权限查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1120, 1109, 'sys:permission:add', '新增权限', 'BUTTON', NULL, 20, 1, '权限新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1121, 1109, 'sys:permission:edit', '修改权限', 'BUTTON', NULL, 21, 1, '权限修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1122, 1109, 'sys:permission:delete', '删除权限', 'BUTTON', NULL, 22, 1, '权限删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1123, 1110, 'sys:dept:view', '查看部门', 'BUTTON', NULL, 23, 1, '部门查询权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1124, 1110, 'sys:dept:add', '新增部门', 'BUTTON', NULL, 24, 1, '部门新增权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1125, 1110, 'sys:dept:edit', '修改部门', 'BUTTON', NULL, 25, 1, '部门修改权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1126, 1110, 'sys:dept:delete', '删除部门', 'BUTTON', NULL, 26, 1, '部门删除权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1127, NULL, '*:*:*', '系统全量权限', 'BUTTON', NULL, 99, 1, '管理员全量权限', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1128, NULL, 'client:view', '客户端管理', 'MENU', '/client', 27, 1, '查看已注册客户端信息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1129, 1128, 'client:delete', '移除客户端', 'BUTTON', NULL, 28, 1, '移除客户端注册信息', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE SYS_PERMISSION SET ICON = 'el-icon-house' WHERE PERMISSION_CODE = 'menu:home';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-upload2' WHERE PERMISSION_CODE = 'menu:deploy';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-collection' WHERE PERMISSION_CODE = 'menu:model';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-edit-outline' WHERE PERMISSION_CODE = 'menu:designer';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-tickets' WHERE PERMISSION_CODE = 'menu:form';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-s-operation' WHERE PERMISSION_CODE = 'menu:process';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-s-check' WHERE PERMISSION_CODE = 'menu:task';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-connection' WHERE PERMISSION_CODE = 'client:view';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-user' WHERE PERMISSION_CODE = 'menu:sys:user';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-s-custom' WHERE PERMISSION_CODE = 'menu:sys:role';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-key' WHERE PERMISSION_CODE = 'menu:sys:permission';
UPDATE SYS_PERMISSION SET ICON = 'el-icon-office-building' WHERE PERMISSION_CODE = 'menu:sys:dept';

INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1130, 1102, 'deploy:tab:create', '创建部署', 'TAB', NULL, 1, 1, '部署中心创建部署', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1131, 1102, 'deploy:tab:list', '流程列表', 'TAB', NULL, 2, 1, '部署中心流程列表', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1132, 1103, 'model:tab:create', '创建模型', 'TAB', NULL, 1, 1, '模型中心创建模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1133, 1103, 'model:tab:list', '模型列表', 'TAB', NULL, 2, 1, '模型中心模型列表', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1134, 1105, 'process:tab:create', '创建流程', 'TAB', NULL, 1, 1, '流程中心创建流程', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1135, 1105, 'process:tab:list', '流程列表', 'TAB', NULL, 2, 1, '流程中心流程列表', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1136, 1102, 'deploy:refresh', '刷新部署', 'BUTTON', NULL, 10, 1, '刷新部署中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1137, 1102, 'deploy:create', '提交部署', 'BUTTON', NULL, 11, 1, '提交流程部署', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1138, 1102, 'deploy:start', '发起审批', 'BUTTON', NULL, 12, 1, '从部署发起审批', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1139, 1102, 'deploy:edit', '编辑部署', 'BUTTON', NULL, 13, 1, '编辑部署流程定义', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1140, 1102, 'deploy:view', '查看部署', 'BUTTON', NULL, 14, 1, '查看部署详情', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1141, 1102, 'deploy:preview', '预览部署', 'BUTTON', NULL, 15, 1, '预览部署流程图', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1142, 1102, 'deploy:binding', '修改部署绑定', 'BUTTON', NULL, 16, 1, '修改部署客户端绑定', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1143, 1102, 'deploy:delete', '删除部署', 'BUTTON', NULL, 17, 1, '删除部署数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1144, 1103, 'model:refresh', '刷新模型', 'BUTTON', NULL, 10, 1, '刷新模型中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1145, 1103, 'model:create', '创建模型', 'BUTTON', NULL, 11, 1, '创建流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1146, 1103, 'model:edit', '修改模型', 'BUTTON', NULL, 12, 1, '修改流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1147, 1103, 'model:preview', '预览模型', 'BUTTON', NULL, 13, 1, '预览流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1148, 1103, 'model:deploy', '部署模型', 'BUTTON', NULL, 14, 1, '部署流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1149, 1103, 'model:delete', '删除模型', 'BUTTON', NULL, 15, 1, '删除流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1150, 1105, 'process:refresh', '刷新流程', 'BUTTON', NULL, 10, 1, '刷新流程中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1151, 1105, 'process:view', '查看流程', 'BUTTON', NULL, 11, 1, '查看流程详情', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1152, 1105, 'process:submit', '提交流程', 'BUTTON', NULL, 12, 1, '提交草稿流程', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1153, 1105, 'process:delete', '删除流程', 'BUTTON', NULL, 13, 1, '删除流程申请', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1154, 1105, 'process:action:draft', '保存草稿', 'BUTTON', NULL, 14, 1, '流程表单保存草稿按钮', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1155, 1105, 'process:action:submit', '提交申请', 'BUTTON', NULL, 15, 1, '流程表单提交申请按钮', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1156, 1105, 'process:action:reset', '重置流程表单', 'BUTTON', NULL, 16, 1, '流程表单重置按钮', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1157, 1106, 'task:refresh', '刷新任务', 'BUTTON', NULL, 10, 1, '刷新任务中心数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1158, 1106, 'task:view', '查看任务', 'BUTTON', NULL, 11, 1, '查看任务流程图', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1159, 1106, 'task:approve', '办理任务', 'BUTTON', NULL, 12, 1, '办理审批任务', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1160, 1106, 'task:delete', '删除任务', 'BUTTON', NULL, 13, 1, '删除任务', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1161, 1128, 'client:refresh', '刷新客户端', 'BUTTON', NULL, 10, 1, '刷新客户端数据', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1162, 1128, 'client:detect', '检测客户端', 'BUTTON', NULL, 11, 1, '检测客户端存活状态', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1163, 1105, 'process:status:tag', '流程状态', 'TAG', NULL, 30, 1, '流程中心状态资源', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1176, 1104, 'designer:save', '保存流程模型', 'BUTTON', NULL, 9, 1, '保存流程设计器内容到流程模型', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1164, 1104, 'designer:export:bpmn', '导出 BPMN', 'BUTTON', NULL, 10, 1, '导出 BPMN 文件', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1165, 1104, 'designer:export:bpmn-xml', '导出 BPMN.XML', 'BUTTON', NULL, 11, 1, '导出 BPMN.XML 文件', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1166, 1104, 'designer:export:png', '导出 PNG', 'BUTTON', NULL, 12, 1, '导出 PNG 图片', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1167, 1104, 'designer:canvas:center', '居中显示', 'BUTTON', NULL, 13, 1, '将画布内容居中显示', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1168, 1104, 'designer:canvas:reset', '清空画布', 'BUTTON', NULL, 14, 1, '清空画布内容', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1169, 1104, 'designer:canvas:refresh', '刷新画布', 'BUTTON', NULL, 15, 1, '刷新画布内容', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1171, 1170, 'form:save', '保存表单方案', 'BUTTON', NULL, 10, 1, '保存表单设计方案', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1172, 1170, 'form:load', '载入表单方案', 'BUTTON', NULL, 11, 1, '载入表单设计方案', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1173, 1170, 'form:export', '导出表单JSON', 'BUTTON', NULL, 12, 1, '导出表单设计JSON', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1174, 1170, 'form:import', '导入表单JSON', 'BUTTON', NULL, 13, 1, '导入表单设计JSON', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO SYS_PERMISSION (ID, PARENT_ID, PERMISSION_CODE, PERMISSION_NAME, PERMISSION_TYPE, ROUTE_PATH, SORT_NO, STATUS, REMARK, CREATE_TIME, UPDATE_TIME) VALUES (1175, 1170, 'form:jump:designer', '跳转流程设计', 'BUTTON', NULL, 14, 1, '从表单设计跳转流程设计', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE SYS_PERMISSION SET SORT_NO = SORT_NO + 1 WHERE PERMISSION_CODE IN ('menu:process', 'menu:task', 'menu:sys:user', 'menu:sys:role', 'menu:sys:permission', 'menu:sys:dept');

INSERT INTO SYS_USER_ROLE (USER_ID, ROLE_ID, CREATE_TIME)
VALUES (1001, 1001, CURRENT_TIMESTAMP);

INSERT INTO SYS_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, CREATE_TIME)
SELECT 1001, ID, CURRENT_TIMESTAMP FROM SYS_PERMISSION;
