CREATE TABLE WCDK_PROCESS_REQUEST (
    ID BIGINT NOT NULL,
    PROCESS_NO VARCHAR(64) NOT NULL,
    STARTER VARCHAR(64) NOT NULL,
    TASK_NAME VARCHAR(255) NOT NULL,
    BUSINESS_TITLE VARCHAR(1000) NOT NULL,
    FORM_DATA_JSON CLOB,
    STATUS VARCHAR(32) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64),
    CURRENT_TASK_ID VARCHAR(64),
    CURRENT_TASK_NAME VARCHAR(128),
    PROCESS_DEFINITION_KEY VARCHAR(128) NOT NULL,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT PK_WCDK_PROCESS_REQUEST PRIMARY KEY (ID)
);

COMMENT ON TABLE WCDK_PROCESS_REQUEST IS '流程申请业务表';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.ID IS '主键';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_NO IS '流程申请编号';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.STARTER IS '流程发起人';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.TASK_NAME IS '任务名称';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.BUSINESS_TITLE IS '业务标题';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.FORM_DATA_JSON IS '动态表单数据JSON';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.STATUS IS '流程申请状态';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_INSTANCE_ID IS '流程实例ID';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CURRENT_TASK_ID IS '当前任务ID';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CURRENT_TASK_NAME IS '当前任务名称';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.PROCESS_DEFINITION_KEY IS '流程定义标识';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WCDK_PROCESS_REQUEST.UPDATE_TIME IS '更新时间';

CREATE UNIQUE INDEX UK_WCDK_PROCESS_REQUEST_NO ON WCDK_PROCESS_REQUEST(PROCESS_NO);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_PROC ON WCDK_PROCESS_REQUEST(PROCESS_INSTANCE_ID);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_DEF_KEY ON WCDK_PROCESS_REQUEST(PROCESS_DEFINITION_KEY);
CREATE INDEX IDX_WCDK_PROCESS_REQUEST_STATUS ON WCDK_PROCESS_REQUEST(STATUS);
