package com.wcdk.process.engine.impl;

import com.wcdk.process.engine.ReactiveAgenda;
import com.wcdk.process.engine.ReactiveRepositoryService;
import com.wcdk.process.engine.ReactiveRuntimeService;
import com.wcdk.process.entity.ExecutionEntity;
import com.wcdk.process.entity.ProcessInstanceEntity;
import com.wcdk.process.enums.ExecutionState;
import com.wcdk.process.enums.ProcessStatus;
import com.wcdk.process.exception.ProcessEngineException;
import com.wcdk.process.execution.ReactiveVariableManager;
import com.wcdk.process.repository.ExecutionRepository;
import com.wcdk.process.repository.ProcessInstanceRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

import java.time.Instant;
import java.util.Map;

@Service
@RequiredArgsConstructor
/**
 * WCDK 流程模块类型。
 *
 * @author WCDK
 * @version 1.0
 */
public class ReactiveRuntimeServiceImpl implements ReactiveRuntimeService {

    private final ProcessInstanceRepository processInstanceRepository;
    private final ExecutionRepository executionRepository;
    private final ReactiveRepositoryService repositoryService;
    private final ReactiveAgenda agenda;
    private final ReactiveVariableManager variableManager;
    private final ReactiveCommandExecutorImpl commandExecutor;

    @Override
    public Mono<ProcessInstanceEntity> startProcessByKey(String processDefinitionKey, String businessKey, String starter, Map<String, Object> variables) {
        return startProcessByKey("default", processDefinitionKey, businessKey, starter, variables);
    }

    @Override
    public Mono<ProcessInstanceEntity> startProcessByKey(String tenantId, String processDefinitionKey, String businessKey, String starter, Map<String, Object> variables) {
        return repositoryService.getLatestProcessDefinitionByKey(tenantId, processDefinitionKey)
                .switchIfEmpty(Mono.error(new ProcessEngineException("Process definition not found: " + processDefinitionKey)))
                .flatMap(pd -> {
                    ProcessInstanceEntity pi = new ProcessInstanceEntity();
                    // ID will be generated by snowflake
                    pi.setTenantId(tenantId);
                    pi.setProcessDefinitionId(pd.getId());
                    pi.setProcessDefinitionKey(pd.getKey());
                    pi.setProcessDefinitionVersion(pd.getVersion());
                    pi.setBusinessKey(businessKey);
                    pi.setRootProcessInstanceId(null);
                    pi.setStarter(starter);
                    pi.setStartTime(Instant.now());
                    pi.setStatus(ProcessStatus.RUNNING.name());
                    pi.setSuspensionState(1);
                    pi.setRevision(1L);
                    pi.setCreatedAt(Instant.now());
                    pi.setUpdatedAt(Instant.now());

                    return processInstanceRepository.insert(pi)
                            .flatMap(savedPi -> {
                                savedPi.setRootProcessInstanceId(savedPi.getId());

                                return repositoryService.getProcessGraph(pd.getId())
                                        .switchIfEmpty(Mono.error(new ProcessEngineException(
                                                "Process graph not found for: " + pd.getId())))
                                        .flatMap(graph -> {
                                ExecutionEntity execution = new ExecutionEntity();
                                execution.setTenantId(tenantId);
                                execution.setProcessInstanceId(savedPi.getId());
                                execution.setProcessDefinitionId(pd.getId());
                                execution.setRootExecutionId(null);
                                execution.setNodeId(graph.getStartNodeId());
                                execution.setNodeType("START_EVENT");
                                execution.setState(ExecutionState.ACTIVE.name());
                                execution.setIsScope(1);
                                execution.setIsConcurrent(0);
                                execution.setIsEventScope(0);
                                execution.setIsMultiInstance(0);
                                execution.setSuspensionState(1);
                                execution.setRevision(1L);
                                execution.setCreatedAt(Instant.now());
                                execution.setUpdatedAt(Instant.now());

                                return executionRepository.insert(execution)
                                        .flatMap(savedExec -> {
                                            savedPi.setRootProcessInstanceId(savedPi.getId());
                                            savedExec.setRootExecutionId(savedExec.getId());
                                            savedExec.setScopeExecutionId(savedExec.getId());

                                            return processInstanceRepository.updateById(savedPi)
                                                    .then(executionRepository.updateById(savedExec))
                                                    .then(Mono.defer(() -> {
                                                        if (variables != null && !variables.isEmpty()) {
                                                            Mono<Void> setVars = Mono.empty();
                                                            for (var entry : variables.entrySet()) {
                                                                setVars = setVars.then(
                                                                        variableManager.setProcessVariable(savedPi.getId(), entry.getKey(), entry.getValue())
                                                                );
                                                            }
                                                            return setVars;
                                                        }
                                                        return Mono.empty();
                                                    }))
                                                    .then(Mono.defer(() -> {
                                                        agenda.planContinueProcessInNode(savedExec.getId(), graph.getStartNodeId());
                                                        return commandExecutor.flushAgenda();
                                                    }))
                                                    .then(Mono.just(savedPi));
                                        });
                            });
                            });
                });
    }

    @Override
    public Mono<ProcessInstanceEntity> getProcessInstanceById(String processInstanceId) {
        return processInstanceRepository.selectById(processInstanceId);
    }

    @Override
    public Mono<Void> suspendProcessInstance(String processInstanceId) {
        return processInstanceRepository.selectById(processInstanceId)
                .flatMap(pi -> {
                    pi.setSuspensionState(2);
                    pi.setUpdatedAt(Instant.now());
                    return processInstanceRepository.updateById(pi);
                })
                .then();
    }

    @Override
    public Mono<Void> activateProcessInstance(String processInstanceId) {
        return processInstanceRepository.selectById(processInstanceId)
                .flatMap(pi -> {
                    pi.setSuspensionState(1);
                    pi.setUpdatedAt(Instant.now());
                    return processInstanceRepository.updateById(pi);
                })
                .then();
    }

    @Override
    public Mono<Void> terminateProcessInstance(String processInstanceId) {
        return processInstanceRepository.selectById(processInstanceId)
                .flatMap(pi -> {
                    pi.setStatus(ProcessStatus.TERMINATED.name());
                    pi.setEndTime(Instant.now());
                    if (pi.getStartTime() != null) {
                        pi.setDurationMs(java.time.Duration.between(pi.getStartTime(), pi.getEndTime()).toMillis());
                    }
                    pi.setUpdatedAt(Instant.now());
                    return processInstanceRepository.updateById(pi);
                })
                .then();
    }

    @Override
    public Mono<Void> suspendExecution(String executionId) {
        return executionRepository.selectById(executionId)
                .flatMap(execution -> {
                    execution.setSuspensionState(2);
                    execution.setUpdatedAt(Instant.now());
                    return executionRepository.updateById(execution);
                })
                .then();
    }

    @Override
    public Mono<Void> activateExecution(String executionId) {
        return executionRepository.selectById(executionId)
                .flatMap(execution -> {
                    execution.setSuspensionState(1);
                    execution.setUpdatedAt(Instant.now());
                    return executionRepository.updateById(execution);
                })
                .then();
    }

    @Override
    public Mono<Void> suspendProcessDefinition(String processDefinitionId) {
        return repositoryService.getProcessDefinitionById(processDefinitionId)
                .switchIfEmpty(Mono.error(new com.wcdk.process.exception.ProcessEngineException("Process definition not found: " + processDefinitionId)))
                .flatMap(pd -> {
                    pd.setSuspended(1);
                    pd.setUpdatedAt(Instant.now());
                    return processInstanceRepository.findByProcessDefinitionId(processDefinitionId)
                            .flatMap(pi -> {
                                pi.setSuspensionState(2);
                                pi.setUpdatedAt(Instant.now());
                                return processInstanceRepository.updateById(pi);
                            })
                            .then(Mono.defer(() -> {
                                executionRepository.findByProcessDefinitionId(processDefinitionId)
                                        .flatMap(execution -> {
                                            execution.setSuspensionState(2);
                                            execution.setUpdatedAt(Instant.now());
                                            return executionRepository.updateById(execution);
                                        })
                                        .subscribe();
                                return Mono.empty();
                            }));
                })
                .then();
    }

    @Override
    public Mono<Void> activateProcessDefinition(String processDefinitionId) {
        return repositoryService.getProcessDefinitionById(processDefinitionId)
                .switchIfEmpty(Mono.error(new com.wcdk.process.exception.ProcessEngineException("Process definition not found: " + processDefinitionId)))
                .flatMap(pd -> {
                    pd.setSuspended(0);
                    pd.setUpdatedAt(Instant.now());
                    return processInstanceRepository.findByProcessDefinitionId(processDefinitionId)
                            .flatMap(pi -> {
                                pi.setSuspensionState(1);
                                pi.setUpdatedAt(Instant.now());
                                return processInstanceRepository.updateById(pi);
                            })
                            .then(Mono.defer(() -> {
                                executionRepository.findByProcessDefinitionId(processDefinitionId)
                                        .flatMap(execution -> {
                                            execution.setSuspensionState(1);
                                            execution.setUpdatedAt(Instant.now());
                                            return executionRepository.updateById(execution);
                                        })
                                        .subscribe();
                                return Mono.empty();
                            }));
                })
                .then();
    }
}